name: Build

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Upload bindings
        uses: actions/upload-artifact@v2
        with:
          name: bindings.rs
          path: "target/debug/build/wally-sys-*/out/bindings.rs"

